depends: global
db:
  host: postgres
  port: 5432
  name: gost
  user: gost
  password: gost
rabbit:
  servers:
    local:
      host: rabbitmq
      vhost: \
      port: 5672
      user: gost
      password: admin
