depends: global
db:
  host: 10.10.10.100
  port: 5433
  name: mpauth
  user: mpauth
  password: mpauth
rabbit:
  servers:
    local:
      host: 127.0.0.1
      vhost: vgost
      port: 5672
      user: gost
      password: gost
